#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_ENV="${1:-"$ROOT_DIR/.env.local"}"

if [[ ! -f "$SOURCE_ENV" ]]; then
  echo "Missing $SOURCE_ENV"
  echo "Create it from .env.example first: cp .env.example .env.local"
  exit 1
fi

write_app_env() {
  local app="$1"
  local better_auth_url="$2"
  local public_auth_url="${3:-}"
  local admin_url="${4:-}"
  local target="$ROOT_DIR/apps/$app/.env.local"

  {
    echo "# Generated by scripts/link-env.sh from $(basename "$SOURCE_ENV")."
    echo "# Do not edit this file directly; update the repo root .env.local instead."
    echo
    awk '!/^(BETTER_AUTH_URL|NEXT_PUBLIC_AUTH_URL|NEXT_PUBLIC_ADMIN_URL)=/' "$SOURCE_ENV"
    echo
    echo "BETTER_AUTH_URL=\"$better_auth_url\""
    if [[ -n "$public_auth_url" ]]; then
      echo "NEXT_PUBLIC_AUTH_URL=\"$public_auth_url\""
    fi
    if [[ -n "$admin_url" ]]; then
      echo "NEXT_PUBLIC_ADMIN_URL=\"$admin_url\""
    fi
  } > "$target"

  echo "Wrote apps/$app/.env.local"
}

write_app_env "api" "http://localhost:3005" "http://localhost:3005"
write_app_env "storefront" "http://localhost:3000" "http://localhost:3005"
write_app_env "dashboard" "http://localhost:3005" "http://localhost:3005"
write_app_env "checkout" "http://localhost:3004" "http://localhost:3005"
write_app_env "admin" "http://localhost:3005" "http://localhost:3005" "http://localhost:3006"
write_app_env "web" "http://localhost:3001" "http://localhost:3005"
write_app_env "docs" "http://localhost:3003" "http://localhost:3005"
